# Generated by Django 5.0.6 on 2024-05-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
