# Generated by Django 5.0.6 on 2024-05-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_student"),
        ("students", "0003_student_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                related_name="enrolled_students", to="courses.course"
            ),
        ),
    ]
