# Generated by Django 5.0.6 on 2024-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_assignments_remove_course_quizzes_and_more"),
        ("students", "0004_alter_student_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="assignments",
            field=models.ManyToManyField(
                related_name="student_assignments", to="courses.assignment"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="quizzes",
            field=models.ManyToManyField(
                related_name="student_quizzes", to="courses.quiz"
            ),
        ),
    ]
