# Generated by Django 5.0.6 on 2024-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_assignments_student_quizzes"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.PositiveBigIntegerField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
