# Generated by Django 5.0.6 on 2024-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_assignments_remove_course_quizzes_and_more"),
        ("students", "0006_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="enrolled_students",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="quizzes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="student_quizzes", to="courses.quiz"
            ),
        ),
    ]
