# Generated by Django 5.0.6 on 2024-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_assignments_remove_course_quizzes_and_more"),
        ("students", "0007_alter_student_courses_alter_student_quizzes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="assignments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="student_assignments",
                to="courses.assignment",
            ),
        ),
    ]
