# Generated by Django 5.0.6 on 2024-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_student_assignments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="assignments",
        ),
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="student",
            name="quizzes",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
