# Generated by Django 5.0.6 on 2024-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_remove_student_assignments_remove_student_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
