# Generated by Django 5.0.6 on 2024-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0002_alter_faculty_options_remove_faculty_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
