# Generated by Django 5.0.6 on 2024-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0003_alter_faculty_faculty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
