# Generated by Django 5.0.6 on 2024-05-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0005_faculty_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="courses",
        ),
    ]
