# Generated by Django 5.0.6 on 2024-05-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_student_alter_course_assignments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="student",
        ),
    ]
