# Generated by Django 5.0.6 on 2024-05-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="Assignments",
        ),
        migrations.RemoveField(
            model_name="course",
            name="quizzes",
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="grade",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="grade",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
