# Generated by Django 5.0.6 on 2024-05-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_assignments_remove_course_quizzes_and_more"),
        ("faculty", "0002_alter_faculty_options_remove_faculty_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_courses",
                to="faculty.faculty",
            ),
        ),
    ]
