# Generated by Django 5.0.6 on 2024-05-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_remove_grade_comments_enrollment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="courses.quiz",
            ),
        ),
    ]
