# Generated by Django 5.0.6 on 2024-05-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_quizgrade_delete_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("score", models.CharField(max_length=10)),
                (
                    "student_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_grade",
                        to="courses.studentquiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
