# Generated by Django 5.0.6 on 2024-05-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_assignmentgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentgrade",
            name="student_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_grade",
                to="courses.studentassignment",
            ),
        ),
    ]
