# Generated by Django 5.0.6 on 2024-05-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_course_faculty"),
        ("faculty", "0005_faculty_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyTeaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses_taught",
                        to="courses.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_teaching",
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "unique_together": {("faculty", "course")},
            },
        ),
    ]
