# Generated by Django 5.0.6 on 2024-05-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_facultyteaching"),
        ("students", "0010_alter_student_created_at_alter_student_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizgrade",
            name="student_quiz",
        ),
        migrations.AlterUniqueTogether(
            name="studentassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentassignment",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="studentassignment",
            name="student",
        ),
        migrations.AlterUniqueTogether(
            name="studentquiz",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentquiz",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="studentquiz",
            name="student",
        ),
        migrations.AddField(
            model_name="assignment",
            name="grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_quizzes",
                to="students.student",
            ),
        ),
        migrations.DeleteModel(
            name="AssignmentGrade",
        ),
        migrations.DeleteModel(
            name="QuizGrade",
        ),
        migrations.DeleteModel(
            name="StudentAssignment",
        ),
        migrations.DeleteModel(
            name="StudentQuiz",
        ),
    ]
